service: serverless-mongo-altas
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  timeout: 30
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST
  getAll:
    handler: src/handlers/getAll.handler
    events:
      - httpApi:
          path: /users
          method: GET
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: GET
  updateUser:
    handler: src/handlers/updateUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: PUT
  deleteUser:
    handler: src/handlers/deleteUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: DELETE
